    <script type="text/javascript" src="js/jquery.1.8.2.js"></script>
    <script type="text/javascript" src="js/jquery.cycle.all.js"></script>
    <script type="text/javascript" src="js/jquery.colorbox.js"></script>
    <script type="text/javascript" src="js/jquery.selectbox.js"></script>
    <script type="text/javascript" src="js/form_validation.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
	<script type="text/javascript" src="js/jquery.ui.widget.min.js"></script>
	<script type="text/javascript" src="js/jquery.ui.accordion.min.js"></script>
	<script type="text/javascript" src="js/cloud-zoom.1.0.2.js"></script>